name: Generate Contribution Cat

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare output folder
        run: |
          rm -rf output
          mkdir output

      - name: Download Cat GIF
        run: |
          curl -L https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif -o output/github-cat.gif

      - name: Deploy to output branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout --orphan output
          git rm -rf .

          mv output/github-cat.gif .
          rm -rf output

          git add github-cat.gif
          git commit -m "Update Contribution Cat"
          git push origin output --force
